### ISSUE TITLE
Error when using MSSQL

### ISSUE THREAD

**Issue by dmarshall4466** [neozhu/CleanArchitectureWithBlazorServer#393]
When I use the default sqlite connection the app loads fine but when I change it to us MSSQL connection I get the below Error:
[12:28:05 ERR ] Unhandled exception in circuit 'MHOaaQdplW_43aYvTPib5ud-AZnwHOJp5N1nyR8CyrA'.
System.AggregateException: One or more errors occurred. (Sequence contains no elements.)
 ---> System.InvalidOperationException: Sequence contains no elements.
   at Fluxor.Blazor.Web.StoreInitializer.OnAfterRender(Boolean firstRender) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor.Blazor.Web\StoreInitializer.cs:line 57

**Comment by Bram1903** [comment]
@neozhu When you have time, can you take a look at this? I don't have a Microsoft SQL Server database set up at the moment.

**Comment by neozhu** [comment]
@dmarshall4466 
please clear local storage in the browser first. F12-> application -> Local Storage

**Comment by dmarshall4466** [comment]
Thanks @neozhu, sorry I thought it was an issue with Fluxor.
Also, I just wanted to say this is a great project which I'm sure will help alot of people, great work :)
One thing that would be helpful would be if you could provide info on how to create a template from your solution, I've managed to do it with template.json but I'm having to rename all of the namespaces each time for Application, Domain, Infrastructure and Blazor.UI.Server + test projects.

**Comment by neozhu** [comment]
@dmarshall4466 
I suggest trying the method that worked for me. The reason for the issue you encountered might be due to the fact that different databases generate different JWT Tokens, which are not interchangeable. Therefore, you may need to delete the existing token and log in again.
<img width="1315" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/060ab244-2f29-46a9-a98f-50db56f888d3">

As for creating a Visual Studio .NET project template, I'm not an expert in that area, so I'm not sure if I can be of much help. However, I recommend looking into the template.json file and renaming the namespaces for the Application, Domain, Infrastructure, and Blazor.UI.Server + test projects. This should help you create a template that suits your needs.

**Comment by Bram1903** [comment]
> Thanks @neozhu, sorry I thought it was an issue with Fluxor.
> Also, I just wanted to say this is a great project which I'm sure will help alot of people, great work :)
> One thing that would be helpful would be if you could provide info on how to create a template from your solution, I've managed to do it with template.json but I'm having to rename all of the namespaces each time for Application, Domain, Infrastructure and Blazor.UI.Server + test projects.

We greatly improved being able to use our template. You can find the updated documentation in the README! 
See #428
