### ISSUE TITLE
[Question] How to do migrations

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#433]
How do you do migrations in this project?

Based on the clean architecture repo (https://github.com/jasontaylordev/CleanArchitecture) I tried this `PS C:\TMP\Blazor\MVP\BlazorClean> dotnet ef migrations add "itemv1" --project src\Infrastructure --startup-project src\Blazor.Server.UI --output-dir Migrators.MSSQL\Migrations`

Resulting in error `Your target project 'CleanArchitecture.Blazor.Infrastructure' doesn't match your migrations assembly 'CleanArchitecture.Blazor.Migrators.MSSQL'. Either change your target project or change your migrations assembly.`

How should the command be for MSSQL?

**Comment by Bram1903** [comment]
Hey @jochem4207,

Try using the following command:

```
dotnet ef migrations add --project src/Migrators/Migrators.MSSQL/Migrators.MSSQL.csproj --startup-project src/Blazor.Server.UI/Blazor.Server.UI.csproj --context CleanArchitecture.Blazor.Infrastructure.Persistence.ApplicationDbContext --configuration Debug yourMigrationName --output-dir Migrations
```

I hope this helps, and otherwise, let me know!

Kind regards,
Bram (Totaal geen Nederlander 😊)

**Comment by jochem4207** [comment]
Dankjewel Bram!
Thank you! :)

I really love this project, so much features (and probably really well done but that's a part i've yet to learn)

**Comment by Bram1903** [comment]
Geen probleem! :-)

@neozhu,
I will update the readme somewhere soon, so it's more clear on how to create migrations. I had the same issue in the beginning, so if we improve the documentation on how to do so, it should be more clear for new users!

**Comment by jochem4207** [comment]
@Bram1903 It's wonderful you going to update the doc. If I may propose also to add a bit about the docker part. Why is there docker in here? How to use it? (How to remove it?, there was a earlier github issue in this repo about it). 

For me, i'm a .NET developer but have been out of programming to long to be up-to-date with docker and stuff. So it was really confusing if I needed to ran some docker command or just run the solution (which didn't work at the first time, probably due some database misconfiguration on my end). So it's definitely a "user" issue and not a issue with the repo. But maybe with this insight you two can set up newbie-friendly doc. 

I'm really enjoying the project. Creating my own pages now and using mudblazor for the first time

**Comment by Bram1903** [comment]
> @Bram1903 It's wonderful you going to update the doc. If I may propose also to add a bit about the docker part. Why is there docker in here? How to use it? (How to remove it?, there was a earlier github issue in this repo about it).
> 
> For me, i'm a .NET developer but have been out of programming to long to be up-to-date with docker and stuff. So it was really confusing if I needed to ran some docker command or just run the solution (which didn't work at the first time, probably due some database misconfiguration on my end). So it's definitely a "user" issue and not a issue with the repo. But maybe with this insight you two can set up newbie-friendly doc.
> 
> I'm really enjoying the project. Creating my own pages now and using mudblazor for the first time

Hey, Docker is a platform that allows you to package and run applications in isolated containers. It provides a consistent environment for your applications to run, regardless of the underlying system. Docker simplifies the process of building, deploying, and managing applications, making it easier to distribute and scale your software. You can basically see it as a simplified virtual machine, which makes sure to remove the "it works on my computer" part since everyone runs it in the same environment on the same operating system. (Often Linux)

I'll try and update the README to make it clear that running the application in Docker is purely optional, and explain shortly what Docker is and what it does! 

Glad to hear that you are enjoying this project, and yeah, MudBlazor is awesome!

**Comment by jochem4207** [comment]
@Bram1903  thank you for the really extensive write up. I couldn't figure out the command for idempotent script and the rider plugin helped so much. You pointed to the plugin to me here. So really helpful <3

**Comment by Bram1903** [comment]
> @Bram1903 thank you for the really extensive write up. I couldn't figure out the command for idempotent script and the rider plugin helped so much. You pointed to the plugin to me here. So really helpful <3

Hey Jochem,

No problem man, that's what we developers do. Whenever possible we try to help each other! 
It is quite a coincidence I added option 3 as well, since most people would use option 1 or 2, but since I always use Rider, because I find it such a great IDE, I thought let's add the option I always use as well!

Kind regards,
Bram
