### ISSUE TITLE
[Bug/Feature/Sample]UTC Times to Local

### ISSUE THREAD

**Issue by bakes82** [neozhu/CleanArchitectureWithBlazorServer#485]
Currently it looks like you are only dealing with UTC times which doesn't always translate well especially when filtering for things like "Created Today".  

You can see the code here, I can PR if you want it.
https://github.com/bakes82/CleanArchitectureWithBlazorServer/tree/UTCToLocal

- Timezone Components can show windows or iana formats (page has both added)
- Add Created to productsdto
- Get timezone from JS
- Calc the UTC from adjusted local time for filter
- Clone button fix (selected items not cleared)
- Changed Colors
- Added MudHighlighter for the search
- In filter used EF.Functions.Like instead of string.contains

![UTCToLocal](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3197191/078a5183-e734-46d1-9e11-0dc33d5c9515)
![HighlighterSearch](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3197191/86d50222-bf43-4e65-b7c7-25677cdf3d66)

**Comment by bakes82** [comment]
Questions:
There is a DateTimeService, it only seems used in the AuditableEntity, so there was some weirdness going on originally for me.  Not sure how you want to address that.

Instead of datetime and forcing UTC why not just datetimeoffset columns?

Any preference on bases vs interfaces?  I added a interface for my clienttimzone field, but I could also say the base filter could also just be a interface, or I could make a new base.

**Comment by Bram1903** [comment]
I partly tried to do this on the logs page, where I used a library which used JavaScript to detect the users timezone, however doing it natively ourselves would probably be much better than using some barely updated library. Using an off set rather than forcing UTC would have my preference as well. 

@neozhu Could you answer his questions? 

As of the way of implementing it, I don't really mind. Whatever you think is the best solution is fine for me as well.

**Comment by bakes82** [comment]
@Bram1903 I used the nuget ref from an older .net solution we have.  I guess apparently in .net6+ its baked in :P the nuget github pointed me there  as for the JS its just straight js Intl.DateTimeFormat().resolvedOptions().timeZone;
https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#time-zone-conversion-apis

Im always going to need to do this as we dont store in UTC usually or store an offset, so I get to "guess" based on the sql server what "default" time zone its in ;), then based on that and knowing where the data comes from the fields might be UTC but the audit cols will be systems, its fun, but hey the DBAs know whats right I guess.

**Comment by Bram1903** [comment]
> @Bram1903 I used the nuget ref from an older .net solution we have.  I guess apparently in .net6+ its baked in :P the nuget github pointed me there  as for the JS its just straight js Intl.DateTimeFormat().resolvedOptions().timeZone;
> 
> https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#time-zone-conversion-apis
> 
> 
> 
> Im always going to need to do this as we dont store in UTC usually or store an offset, so I get to "guess" based on the sql server what "default" time zone its in ;), then based on that and knowing where the data comes from the fields might be UTC but the audit cols will be systems, its fun, but hey the DBAs know whats right I guess.
> 
> 

Oww, that's actually interesting! If you want we can store everything in UtcNow or store the off set? PostgreSQL only supports UtcNow, so I had to add a line when setting up the application database context (See [Line 13](https://github.com/neozhu/CleanArchitectureWithBlazorServer/blob/main/src/Infrastructure/Extensions/DbContextOptionsBuilderExtensions.cs) which enables legacy behaviour, and just turns everything in UTC, so when using PostgrSQL everything should be fine, but I rather implement it consistently throughout the entire project!

**Comment by bakes82** [comment]
Yeah I work in marketing and all our db stuff is done by the db team so I don’t ever use ef migrations and we only use sql so seeing datetime.now but then the db has utc was weird mechanics.  But yeah lots of data from multi platforms and syncing them is my core and the db people starting to see how I always push back for utc or offset when I’m like then your views/stored procs need to figure out the times to align things.  So maybe just inject the date services some place I just don’t know where yet.  I placed it someplace but was a bunch of refactoring was needed and I was like I’ll see about doing it in my azure storage tables/cosmos.

**Comment by Bram1903** [comment]
Yeah, seeing `DateTime.Now` being used in the code while in the database `DateTime.UtcNow` is being used, is indeed rather confusing. I got used to it by now, but I can imagine that at first, this is extremely confusing. 

Personally, I think we should try and implement time storing way more consistently throughout the project, by either just storing everything in `DateTime.UtcNow` or by storing the offset value as well. Either way, that's better than we currently have.

Because I'm using PostgreSQL as a database provider I don't really have to worry a time stored in anything other than `DateTime.UtcNow`, because when using Npgsql, which is the open source EF Core provider for PostgreSQL, I have `Npgsql.EnableLegacyTimestampBehavior` enabled, which automatically converts any timezone back to `DateTime.UtcNow`. This is needed because PostgreSQL doesn't support any time storing other than UTC.

However, in my opinion, it's not a good habit to depend on this sort of legacy behavior switches, and therefore @neozhu we really need to think about the way we store our `datetime` data type. I brought this up before when I tried to make the logs page show the log time in every user their own timezone, which works great, however implementing a steady and consistent factor, would improve the code a lot as well. There are multiple ways that we can implement it. One of them is just storing everything in UTC, and the other is by storing the time offset, which is considered best practice these days I'm pretty sure.
