### ISSUE TITLE
identity id as Guid instead of string

### ISSUE THREAD

**Issue by madhusudhan-v** [neozhu/CleanArchitectureWithBlazorServer#488]
To make progress on storage and performance,cant we make it Guid instead of string. I tried but not completed and also main reason is if i tried then cant merge with main branch,so can you try.

Ex: IdentityUser<Guid> instead of IdentityUser<string>, mainly in terms of memory 4 times saves and also perfonrmance is very fast in terms of indexing as well

**Comment by neozhu** [comment]
@madhusudhan-v,

Thank you for your suggestion on improving storage and performance by using Guid instead of string. 
Your insights into memory savings and performance improvements in terms of indexing are valuable.

However, implementing Guid as the primary key instead of an auto-incrementing int would require a complete refactoring of all EF Core code. While this approach could potentially lead to enhancements, it would indeed be a significant undertaking.

In response to your suggestion, I believe a feasible approach would be to begin refactoring by replacing `BaseEntity` with `BaseEntity<T>`. This change would allow support for various types of primary keys, providing more flexibility. 

If you're interested in taking on this task, please feel free to create a PR. I'm excited to see how this change could evolve, and I'll be glad to review and collaborate with you on this matter.
