### ISSUE TITLE
For Dotnet 6

### ISSUE THREAD

**Issue by erdikalleci** [neozhu/CleanArchitectureWithBlazorServer#550]
Is there a similarly fully functional system for Dotnet 6?

**Comment by Bram1903** [comment]
Hello @erdikalleci 

You can just change the properties of the projects back to .NET, since almost everything should be backwards compatible, however as Matteo mentions above, why would you ever want to downgrade to .NET6? The performance improvements between.NET6 and .NET7 is massive! Besides that we will be updating this project too .NET8 in around two weeks, since .NET8 is set to release on November 14. 

If you have another question or like to respond to this message, feel free to do so! 

Kind regards,
Bram

**Comment by Bram1903** [comment]
Considered resolved. Reopen if you have another question.
