### ISSUE TITLE
[Question] Development of this project

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#562]
Hey @neozhu @Bram1903 

Just a question if you have the time and if this is okay to answer publicly. I'm still using your project and I'm eager to learn more about it. Diving myself into technologies and everything. Is there anything you can/want to share about the development of this project. Like what kind of problems you faced, important decisions you made up front (if you can still remember) or during the project. 

I'm so happy that this project exists, it really helps me. Going to check out all that has changed in the past months and can't wait for the .NET 8 Relase <3

Greetings,
Jochem

Also; I know you guys already don't have much time, so if there is no time for this, just close it!

**Comment by neozhu** [comment]
Hi Jochem,

First off, thank you so much for your continued interest and support in our project. It's always encouraging to hear about the positive impact it has on our users.

Currently, the main challenge we're facing with the project, despite upgrading to .NET 8, is the inability to implement component-level mixed rendering modes due to the project's structure. At this stage, this presents an unsolvable issue, so we are supporting server-side rendering modes.

I have already developed several projects using this template. My aim is to continually refine and enhance the template through more practical projects. I'm always open to incorporating new ideas that reduce repetitive coding and add commonly used functionalities. My goal is to make future projects simpler and more efficient.

If you have any ideas or suggestions that you believe could contribute to this goal, I'd be more than happy to consider them for inclusion in the template.

Thanks again for your enthusiasm and support!

**Comment by jochem4207** [comment]
Hey @neozhu thank you for your quick reply! With "component-level mixed rendering modes" do you mean you want to combine blazor server and blazor wasm? or more like blazor/react/angular? 

I love the aim for it and I have the same idea with this template within the company I work for. I love the goal to make it less repetitive. (I love to offer PR's in the future, if I continue this job) but first I want to fully understand the template and learn to submit quality code. When I get new ideas I will keep you posted! I love already how good the excel and pdf feautures are! How you have worked on the code generator tool & so much more!

<3
