### ISSUE TITLE
I have the .NET 8 SDK installed, but solution won't build

### ISSUE THREAD

**Issue by JwanKhalaf** [neozhu/CleanArchitectureWithBlazorServer#573]
Hello

I have just cloned your repository and wanted to build the solution and give it a try. But I get the following:

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/42877376/4a9bc6fd-cf17-4780-947c-ae7a2820d612)

As you can see, I do have the .NET 8 SDK installed.

Is something else required? I had a read of the README but didn't see anything that might explain the above.

**Comment by Bram1903** [comment]
Hello @JwanKhalaf,

It seems like the error you're encountering is due to multiple projects in the current folder, and the system is unsure which one to build. To resolve this, specify the solution file explicitly when using the `dotnet build` command. In your case, you can use the following command:

```bash
dotnet build CleanArchitecture.Blazor.sln
```

This command tells the .NET CLI to build the entire solution specified in the solution file (`CleanArchitecture.Blazor.sln`). This way, it will compile all the projects within the solution.

Feel free to reach out if you encounter any more issues.

Best regards,
Bram

**Comment by JwanKhalaf** [comment]
Thanks @Bram1903, that was it!

I'm confused though, there is only one `.sln` file in that directory.

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/42877376/83439bd6-f24f-4093-a075-a1228543dbe5)

**Comment by Bram1903** [comment]
> Thanks @Bram1903, that was it!
> 
> I'm confused though, there is only one `.sln` file in that directory.
> 
> ![image](https://private-user-images.githubusercontent.com/42877376/291631117-83439bd6-f24f-4093-a075-a1228543dbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTkzOTQsIm5iZiI6MTcwMjk5OTA5NCwicGF0aCI6Ii80Mjg3NzM3Ni8yOTE2MzExMTctODM0MzliZDYtZjI0Zi00MDkzLWEwNzUtYTEyMjg1NDNkYmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMWEzMjQ2OTYyNTY4MTg3NWJhZmY3ODNiYmM4YjQ0ZDk2ZDI2YzQ3ZTJmYTAwNWJiM2E4YWY1YTdiNDMxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUHLpXrhceYSy-wXRDJiIANLP3TRAjiF7ODsJBrknrA)

I think that the .NET CLi also sees `docker-compose.dcproj` as a project file, and therefore it doesn't know which file to build.

**Comment by JwanKhalaf** [comment]
Thanks, I didn't know that <3
