### ISSUE TITLE
Azure deployment ysing cicd , converting to Server Auto+wasm , server side login

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#638]
Hi Neo, Can you help in any of the following. 
1. Signin by server side mode instead of js clientside as easy to bypass. I spent more than to do it a day for this but i failed
2. Blazor server to Auto mode & using the benefits of clientside wasm. Also Currently after idle time it goes to dead state then user has to full refresh even retry also wont work. https://stackoverflow.com/questions/59779601/auto-reconnect-blazor-serverside

4. Some guide for deploying to azure with troubleshooting , currently am trying but facing problem in CI/CD but direct deployment is working fine.

**Comment by nammadhu** [comment]
When deployed within sometime getting below Error as timeout ...
Especially on mobile device... attaching the snapshot here...
Can you please guide asap...
![Screenshot_20240319_090640_Chrome](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/3ef4ac7d-fefe-4897-ae47-296293e0f718)

**Comment by neozhu** [comment]
> When deployed within sometime getting below Error as timeout ... Especially on mobile device... attaching the snapshot here... Can you please guide asap... ![Screenshot_20240319_090640_Chrome](https://private-user-images.githubusercontent.com/3640748/313906400-3ef4ac7d-fefe-4897-ae47-296293e0f718.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjc5NzYsIm5iZiI6MTcxMDgyNzY3NiwicGF0aCI6Ii8zNjQwNzQ4LzMxMzkwNjQwMC0zZWY0YWM3ZC1mZWZlLTQ4OTctYWU0Ny0yOTYyOTNlMGY3MTguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDU1NDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVhNzZiNzZkNDc3ZmVmOWEyYjE5NjZlNmIxZWI2MzI2MWVlMWQ5MGZlNGFkYjMyOTJmYzhkYTUxOTFkZjk0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OUfOrjkObTsbBC5ErUaqTDl_hyqKfO9HSDJN-jbINhE)

It's hard to identify the issue without seeing the snapshot. If it works locally via IIS, it should work with an external domain too. This project uses Docker, which might help, especially on a Linux server. Can you share more details or the snapshot?

**Comment by neozhu** [comment]
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/3e116775-c314-47c4-a287-139dc0e10d4d)
You can check for any error messages by debug console, or you can press f12 in the browser to see the error message

**Comment by nammadhu** [comment]
actually its not occurring locally , its relecting on deployed network only... i tried on multiple types but result is same...

**Comment by neozhu** [comment]
> Hi Neo, Can you help in any of the following.
> 
> 1. Signin by server side mode instead of js clientside as easy to bypass. I spent more than to do it a day for this but i failed
> 2. Blazor server to Auto mode & using the benefits of clientside wasm. Also Currently after idle time it goes to dead state then user has to full refresh even retry also wont work. https://stackoverflow.com/questions/59779601/auto-reconnect-blazor-serverside
> 3. Some guide for deploying to azure with troubleshooting , currently am trying but facing problem in CI/CD but direct deployment is working fine.

1. Signin by server side mode instead of js clientside as easy to bypass. I spent more than to do it a day for this but i failed
answer: It's possible, but not supported in InteractiveServerRenderMode. The pages related to user login can only run under Razor Page mode. Refer to the official code:
```c#
@code {
    [CascadingParameter]
    private HttpContext HttpContext { get; set; } = default!;

    private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
        ? null
        : InteractiveAuto;
}
```

2. Blazor server to Auto mode & using the benefits of clientside wasm. Also Currently after idle time it goes to dead state then user has to full refresh even retry also wont work. https://stackoverflow.com/questions/59779601/auto-reconnect-blazor-serverside
answer: Please refer to the official project template for Global auto render mode. If you want to implement automatic mode switching, then all your blazor pages and components must be in the Client project, and the project SDK must be 'Microsoft.NET.Sdk.BlazorWebAssembly' to be supported. Currently, my project cannot achieve this.

3. Some guide for deploying to azure with troubleshooting , currently am trying but facing problem in CI/CD but direct deployment is working fine.
answer: You can find some action scripts which should make it easy to achieve. Since I don't have an Azure server, I can't help you with that.

**Comment by nammadhu** [comment]
Hi Neo, Thanks for detailed explaination.
1> Signin server side: I tried to make InteractiveAutoRenderMode but failed even after lot of modification.
2+3> Blazor Server auto mode, i have tried all the ways of reconnection, autostart  but still it fails. Actually it fails even on local also, but you have to run for longer. It looks like even Microsoft also not having clear answers for this.

Actually Today I started to add facebook authentication in similar to existing google & microsoft but thats also some problem exists for me. If you have some ready code please share, it helps

**Comment by neozhu** [comment]
> 
For adding Facebook authentication, I also tried registering an application as an individual user but faced issues since it seems not fully supported for individuals. This makes it tricky to publish the application. From my experience and what I've gathered, if you can get past the registration hurdle, implementing Facebook authentication should be similar to Google's.
