### ISSUE TITLE
Current domain event dispatcher does not allow atomic domain event handling.

### ISSUE THREAD

**Issue by carlsixsmith-moj** [neozhu/CleanArchitectureWithBlazorServer#690]
The dispatching of domain events currently won't work if you want to change the state of a different entity in an event listener.

Domain events should be consistent within a bounded context at the moment they are fired AFTER the entity has been saved and they aren't wrapped in any form of transaction.

Is this a design choice or oversite?

**Comment by neozhu** [comment]
Do you have any good solutions for this? I haven't considered transactions; I just want to implement notifications to subscribers for create, update, and delete operations. Additionally, since the entity ID is auto-incremented, I need to obtain the ID of the newly created entity, as this is crucial for subsequent business operations.

**Comment by neozhu** [comment]
Sure, please create a pull request for this. I will review it and merge it."
