### ISSUE TITLE
Issue with AuditableEntityInterceptor and IScopedMediator

### ISSUE THREAD

**Issue by Alywan** [neozhu/CleanArchitectureWithBlazorServer#799]
In my project, after updating your recent changes on the CurrentUserSession (renamed as CurrentUserAccessor) : 

In the AuditableEntityInterceptor, i found out that after submitting changes from any FormDialogs, the _currentUserAccessor.SessionInfo was null, so basically i receive an error because tenantId was null when trying to save in the DB.

Now, i found the cuplrit : 
The IScopedMediator, used in the _Imports.Razor. When using the Mediator, this thing happened.

I tried to insert a new instance of the mediator in my xxxxxFormDialog ([Inject] private IMediator _mediator { get; set; } = default!;) , and now the _currentUserAccessor.SessionInfo has all the data needed.

This is what ClaudeAI said about this issue : 

The scoped mediator might be creating a new scope for each operation, which could be losing the user context when combined with the audit interceptor.
Using the base IMediator interface directly maintains the original scope where the user context is properly initialized.
To fix this consistently across your application, you should:
Either update all your components to use the base IMediator:
[Inject] private IMediator _mediator { get; set; } = default!;

Or ensure your IScopedMediator implementation properly maintains the scoped context:
public class ScopedMediator : IScopedMediator
{
    private readonly IMediator _mediator;
    private readonly IServiceProvider _serviceProvider;

    public ScopedMediator(IMediator mediator, IServiceProvider serviceProvider)
    {
        _mediator = mediator;
        _serviceProvider = serviceProvider;
    }

    public async Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)
    {
        using var scope = _serviceProvider.CreateScope();
        return await _mediator.Send(request, cancellationToken);
    }
    
    // Implement other IMediator members similarly
}

**Comment by neozhu** [comment]
Thank you for pointing this out. I encountered the same issue and now understand the root cause. Looking back, I can't recall the specific reason for originally implementing the `ScopedMediator` class. However, if we follow your approach and use the base `IMediator` directly, it does seem to remove the need for `ScopedMediator`.

To resolve this on my end, I have adjusted `CurrentUserAccessor.cs` by adding two new properties that retrieve data directly from `HttpContext`. This way, the user context is maintained without needing additional scopes.
